// app/settings/page.tsx
"use client";
"use client";

import { Card, CardBody, Select, SelectItem, Switch } from "@nextui-org/react";
import { Icon } from "@iconify/react";
import { useSettingsStore } from "@/store/useSettingsStore";

export default function SettingsPage() {
  const {
    darkMode,
    editDataSaveLocal,
    expandTabs,
    editorCDN,
    setDarkMode,
    setEditDataSaveLocal,
    setExpandTabs,
    setEditorCDN,
  } = useSettingsStore();

  const editorLoadOptions = [
    { label: "本地嵌入", value: "false" },
    { label: "远程CDN", value: "true" },
  ];

  const handleSettingChange = (key: string, value: any) => {
    switch (key) {
      case "darkMode":
        setDarkMode(value);
        break;
      case "editDataSaveLocal":
        setEditDataSaveLocal(value);
        break;
      case "expandTabs":
        setExpandTabs(value);
        break;
      case "editorCDN":
        setEditorCDN(value);
        reloadApp();
        break;
    }
  };

  const reloadApp = () => {
    // 重载应用的逻辑
    console.log("App需要重新加载");
  };

  return (
    <div className="w-full max-w-4xl flex-1 p-4">
      {/* Title */}
      <div className="ml-2">
        <div className="flex items-center gap-x-3">
          <h1 className="text-3xl font-bold leading-9 text-default-foreground">
            设置
          </h1>
          <Icon
            className="flex-none rotate-180 text-default-500"
            icon="solar:settings-outline"
            width={24}
          />
        </div>
        <h2 className="mt-2 text-small text-default-500 flex">
          自定义设置偏好，让你的编辑器更加舒适
        </h2>
      </div>

      <Card fullWidth className="mt-6 py-3 px-2" radius="sm">
        <CardBody>
          <h2 className="text-lg font-medium text-default-900 mb-4">
            常规设置
          </h2>

          {/* 夜间模式 */}
          <div className="flex items-center justify-between py-3 border-b dark:border-default-200">
            <div>
              <p className="text-default-900">深色模式</p>
              <p className="text-sm text-default-500">
                切换深色主题以保护眼睛
              </p>
            </div>
            <Switch
              isSelected={darkMode}
              onValueChange={(value) => handleSettingChange("darkMode", value)}
            />
          </div>

          {/* 本地存储 */}
          <div className="flex items-center justify-between py-3 border-b dark:border-default-200">
            <div>
              <p className="text-default-900">本地存储</p>
              <p className="text-sm text-default-500">
                将编辑器数据存储在本地，关闭后刷新页面数据将丢失
              </p>
            </div>
            <Switch
              isSelected={editDataSaveLocal}
              onValueChange={(value) =>
                handleSettingChange("editDataSaveLocal", value)
              }
            />
          </div>

          {/* Tab展开 */}
          <div className="flex items-center justify-between py-3 border-b dark:border-default-200">
            <div>
              <p className="text-default-900">展开Tab栏</p>
              <p className="text-sm text-default-500">
                设置Tab栏是否默认展开
              </p>
            </div>
            <Switch
              isSelected={expandTabs}
              onValueChange={(value) => handleSettingChange("expandTabs", value)}
            />
          </div>

          {/* 编辑器加载方式 */}
          <div className="flex items-center justify-between py-3">
            <div>
              <p className="text-default-900">编辑器加载方式</p>
              <p className="text-sm text-default-500">
                1. 本地加载，首屏加载速度快，暂不支持中文。
                <br />
                2. CDN(需联网)，首屏加载速度稍慢，支持中文。
              </p>
            </div>
            <Select
              className="w-[220px]"
              label="加载方式"
              selectedKeys={[editorCDN]}
              onChange={(e) => handleSettingChange("editorCDN", e.target.value)}
            >
              {editorLoadOptions.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </Select>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}

// src/pages/settings.vue
<script setup lang="ts" generic="T extends any, O extends any">
import { Button, message, notification } from 'ant-design-vue'
import { storeToRefs } from 'pinia'
import { useRouter } from 'vue-router'
import { useSettingsStore } from '~/stores/settings'
import {STORAGE_KEY} from "~/stores/sidebar";

defineOptions({
  name: 'SettingPage',
})

const router = useRouter()
const settingsStore = useSettingsStore()
const { settings } = storeToRefs(settingsStore)

const editorLoadOptions = [
  { label: '本地嵌入', value: 'false' },
  { label: '远程CDN', value: 'true' },
]

function reloadApp() {
  if (window.utools) {
    console.log(window.utools)
    message.success('重启插件后生效')
    return undefined
  }
  notification.open({
    message: '配置已保存',
    description: '编辑器加载方式已更改，请重新加载或刷新后生效',
    placement: 'bottomRight',
    btn: () =>
      h(
        Button,
        {
          type: 'primary',
          size: 'small',
          onClick: () => location.reload()
          ,
        },
        { default: () => '重新加载' },
      ),
  })
}

function editorCDNChange(value: string) {
  if (value !== settings.editorCDN) {
    reloadApp()
  }
}

function editDataSaveLocalChange(value: boolean) {
  if (!value) {
    localStorage.removeItem(STORAGE_KEY)
  }
}
</script>

<template>
  <div class="h-full bg-gray-50 dark:bg-dark transition-colors duration-300">
    <a-page-header
      title="插件设置"
      class="h-10 border-b dark:border-neutral-800 py-0.5 bg-white dark:bg-neutral-900 transition-colors duration-300"
      @back="() => useNavigation(router).goBack()"
    />

    <div class="max-w-4xl mx-auto h-full">
      <!-- 设置组 -->
      <div
        class="bg-white dark:bg-neutral-900 rounded-lg shadow-sm p-6 transform transition-all duration-300 h-full"
      >
        <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100 mb-4">
          常规设置
        </h2>

        <!-- 夜间模式 -->
        <div class="flex items-center justify-between py-3 border-b dark:border-neutral-700">
          <div>
            <div class="text-gray-900 dark:text-gray-100">
              深色模式
            </div>
            <div class="text-sm text-gray-500 dark:text-gray-400">
              切换深色主题以保护眼睛
            </div>
          </div>
          <a-switch
            v-model:checked="settings.darkMode"
            class="transition-opacity duration-200 hover:opacity-80"
          />
        </div>
        <!-- 夜间模式 -->
        <div class="flex items-center justify-between py-3 border-b dark:border-neutral-700">
          <div>
            <div class="text-gray-900 dark:text-gray-100">
              本地存储
            </div>
            <div class="text-sm text-gray-500 dark:text-gray-400">
              将编辑器数据存储在本地，关闭后刷新页面数据将丢失。
            </div>
          </div>
          <a-switch
            v-model:checked="settings.editDataSaveLocal"
            class="transition-opacity duration-200 hover:opacity-80"
            @change="editDataSaveLocalChange"
          />
        </div>

        <!-- Tab展开 -->
        <div class="flex items-center justify-between py-3  border-b dark:border-neutral-700">
          <div>
            <div class="text-gray-900 dark:text-gray-100">
              展开Tab栏
            </div>
            <div class="text-sm text-gray-500 dark:text-gray-400">
              设置Tab栏是否默认展开
            </div>
          </div>
          <a-switch
            v-model:checked="settings.expandTabs"
            class="transition-opacity duration-200 hover:opacity-80"
          />
        </div>

        <!-- 编辑器加载方式 -->
        <div class="flex items-center justify-between py-3">
          <div>
            <div class="text-gray-900 dark:text-gray-100">
              编辑器加载方式
            </div>
            <div class="text-sm text-gray-500 dark:text-gray-400">
              1. 本地加载，首屏加载速度快，暂不支持中文。
              <br>
              2. CDN(需联网)，首屏加载速度稍慢，支持中文。
            </div>
          </div>
          <a-select
            v-model:value="settings.editorCDN"
            :options="editorLoadOptions"
            style="width: 120px"
            class="transition-opacity duration-200 hover:opacity-80"
            @change="editorCDNChange"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
:deep(.ant-page-header-heading-title) {
  @apply text-neutral-700 dark:text-neutral-300 text-lg;
}

:deep(.ant-radio-button-wrapper-checked) {
  @apply bg-blue-500 border-blue-500 text-white;
}

:deep(.ant-radio-group-solid .ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled)) {
  @apply bg-blue-500 border-blue-500;
}
</style>
